add coveralls ci
CraftAcademy/broke_no_more pull request #4
Opened 2018-02-26 18:06 UTC by AKidd95

#### PT Story: https://www.pivotaltracker.com/story/show/155515542
#### Description

* add coveralls continuous integration 

#### What I have learned working on this feature: 
I learned how to setup coveralls even better than I did before

2018-02-26 18:23 UTC, magnus-thor commented on Gemfile
> +  gem 'coveralls', require: false
Try to fix the indentation.

2018-02-26 18:23 UTC, magnus-thor commented on Gemfile
> +  gem 'coveralls', require: false
If it looks good in your ide like it did with antonella, delete both lines and write them again.

2018-02-26 19:08 UTC, magnus-thor commented on README.md
> +* etc
The readme should have a separate PR.

2018-02-26 19:08 UTC, magnus-thor commented on coverage/.resultset.json
> +}
Remove coverage files from git.

2018-02-26 19:57 UTC, diraulo requested changes
You actually don't need to have this `coveralls.yml` file here. You should add this token as an environment variable on Semaphore.

2018-02-26 19:57 UTC, diraulo commented on config/coveralls.yml
> +repo_token: ydfjrASHoqWlKe30gExizi5eubrBh0ZjZ
You don't want to track sensitive information like tokens in version control.

2018-02-26 20:00 UTC, diraulo commented on .gitignore
> +/coverage.data
replace these 2 lines with `coverage` it should take care of excluding the entire folder

2018-02-27 08:26 UTC, diraulo commented
Okay I see you've added Coveralls to the story on PT. You should probably change the title of this PR to reflect what you're doing. eg `Setup continuous integration and coverage report`

As for Coveralls you're only setting it up for RSpec. What about Cucumber? And also you should probably merge both reports

2018-02-27 10:30 UTC, magnus-thor commented
Looks good, good job.

2018-02-27 10:30 UTC, merged